routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
})->name('/');

Route::view('messages', 'posts.messages')->name('messages');
//Route::livewire('messages', 'posts.messages')->name('messages');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// user routes
Route::group(['prefix' => 'user', 'as' => 'user.', 'middleware' => ['user']], function () {
	Route::get('/profile', 'Profile\ProfileController@profile')->name('profile');

	// ajax
	Route::get('/get-states', 'User\ProfileController@getStates')->name('get-states');
});

// recruiter routes
Route::group(['prefix' => 'recruit', 'as' => 'recruit.', 'middleware' => ['recruit']], function () {
	//
});

// admin routes
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['admin']], function () {
	// dashboard
	Route::get('/dboard', 'Dboard\DboardController@dboard')->name('dboard');
});

// system routes
Route::group(['prefix' => 'system', 'as' => 'system.', 'middleware' => ['system']], function () {
	//
});

app/Http/Controllers/Dboard/DboardController.php
<?php

namespace App\Http\Controllers\Dboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Auth;

use App\Models\AppInfo;

class DboardController extends Controller
{
    public function __construct()
    {
        $this->middleware('admin');
    }

    public function dboard()
    {
    	return view('dboard.dboard');
    }
}

app/Http/Livewire/User/Inc/ProfileSettings.php
<?php

namespace App\Http\Livewire\User\Inc;

use Livewire\Component;
use App\Models\User\ProfileSettingsModel;
use App\Models\User\Property;
use App\Models\User\Profile;
use Auth;

class ProfileSettings extends Component
{
	public $profileSettings;
	public $dobId, $dobStatus, $dobPrivacy;
	public $contactInfoId, $contactInfoStatus, $contactInfoPrivacy;
	public $interestId, $interestStatus, $interestPrivacy;
	public $socialNetworkId, $socialNetworkStatus, $socialNetworkPrivacy;
	public $educationId, $educationStatus, $educationPrivacy, $educationSerialNo;
	public $experienceId, $experienceStatus, $experiencePrivacy, $experienceSerialNo;
	public $languageId, $languageStatus, $languagePrivacy, $languageSerialNo;
	public $certificationId, $certificationStatus, $certificationPrivacy, $certificationSerialNo;
	public $courseId, $courseStatus, $coursePrivacy, $courseSerialNo;
	public $patentId, $patentStatus, $patentPrivacy, $patentSerialNo;
	public $publicationId, $publicationStatus, $publicationPrivacy, $publicationSerialNo;
	public $organizationClubId, $organizationClubStatus, $organizationClubPrivacy, $organizationClubSerialNo;
	public $honorAwardId, $honorAwardStatus, $honorAwardPrivacy, $honorAwardSerialNo;
	public $testId, $testStatus, $testPrivacy, $testSerialNo;
	public $projectId, $projectStatus, $projectPrivacy, $projectSerialNo;
	public $volanteerSocialworkId, $volanteerSocialworkStatus, $volanteerSocialworkPrivacy, $volanteerSocialworkSerialNo;
	public $extraCurriculumnId, $extraCurriculumnStatus, $extraCurriculumnPrivacy, $extraCurriculumnSerialNo;
	public $recommandationId, $recommandationStatus, $recommandationPrivacy, $recommandationSerialNo;
	public $editMode = false;
	public $properties = [];

	protected $listeners = ['editProfileSettings' => 'editProfileSettings'];

    public function render()
    {
        return view('livewire.user.inc.profile-settings');
    }

    public function getPropertyIds($id)
    {
    	if(!in_array($id, $this->properties))
    	{
    		array_push($this->properties, $id);
    	}
    }

    public function editProfileSettings()
    {
    	$records = ProfileSettingsModel::with('property')->where('user_id',Auth::user()->id)->get();

        foreach ($records as $propertySetting) {

            if($propertySetting->property->name == 'DOB'){
                $this->dobId = $propertySetting->id;
                $this->dobStatus = $propertySetting->status;
                $this->dobPrivacy = $propertySetting->privacy;
            }elseif($propertySetting->property->name == 'CONTACT_INFO'){
                $this->contactInfoId = $propertySetting->id;
                $this->contactInfoStatus = $propertySetting->status;
                $this->contactInfoPrivacy = $propertySetting->privacy;
            }elseif($propertySetting->property->name == 'SOCIAL_NETWORK'){
                $this->socialNetworkId = $propertySetting->id;
                $this->socialNetworkStatus = $propertySetting->status;
                $this->socialNetworkPrivacy = $propertySetting->privacy;
            }elseif($propertySetting->property->name == 'INTEREST'){
                $this->interestId = $propertySetting->id;
                $this->interestStatus = $propertySetting->status;
                $this->interestPrivacy = $propertySetting->privacy;
            }elseif($propertySetting->property->name == 'EDUCATION'){
                $this->educationId = $propertySetting->id;
                $this->educationStatus = $propertySetting->status;
                $this->educationPrivacy = $propertySetting->privacy;
                $this->educationSerialNo = $propertySetting->serial_no;
            }elseif($propertySetting->property->name == 'EXPERIENCE'){
                $this->experienceId = $propertySetting->id;
                $this->experienceStatus = $propertySetting->status;
                $this->experiencePrivacy = $propertySetting->privacy;
                $this->experienceSerialNo = $propertySetting->serial_no;
            }elseif($propertySetting->property->name == 'LANGUAGE'){
                $this->languageId = $propertySetting->id;
                $this->languageStatus = $propertySetting->status;
                $this->languagePrivacy = $propertySetting->privacy;
                $this->languageSerialNo = $propertySetting->serial_no;
            }elseif($propertySetting->property->name == 'CERTIFICATION'){
                $this->certificationId = $propertySetting->id;
                $this->certificationStatus = $propertySetting->status;
                $this->certificationPrivacy = $propertySetting->privacy;
                $this->certificationSerialNo = $propertySetting->serial_no;
            }elseif($propertySetting->property->name == 'COURSE'){
                $this->courseId = $propertySetting->id;
                $this->courseStatus = $propertySetting->status;
                $this->coursePrivacy = $propertySetting->privacy;
                $this->courseSerialNo = $propertySetting->serial_no;
            }elseif($propertySetting->property->name == 'PATENT'){
                $this->patentId = $propertySetting->id;
                $this->patentStatus = $propertySetting->status;
                $this->patentPrivacy = $propertySetting->privacy;
                $this->patentSerialNo = $propertySetting->serial_no;
            }elseif($propertySetting->property->name == 'PUBLICATION'){
                $this->publicationId = $propertySetting->id;
                $this->publicationStatus = $propertySetting->status;
                $this->publicationPrivacy = $propertySetting->privacy;
                $this->publicationSerialNo = $propertySetting->serial_no;
            }elseif($propertySetting->property->name == 'ORGANIZATION_CLUB'){
                $this->organizationClubId = $propertySetting->id;
                $this->organizationClubStatus = $propertySetting->status;
                $this->organizationClubPrivacy = $propertySetting->privacy;
                $this->organizationClubSerialNo = $propertySetting->serial_no;
            }elseif($propertySetting->property->name == 'HONOR_AWARD'){
                $this->honorAwardId = $propertySetting->id;
                $this->honorAwardStatus = $propertySetting->status;
                $this->honorAwardPrivacy = $propertySetting->privacy;
                $this->honorAwardSerialNo = $propertySetting->serial_no;
            }elseif($propertySetting->property->name == 'TEST'){
                $this->testId = $propertySetting->id;
                $this->testStatus = $propertySetting->status;
                $this->testPrivacy = $propertySetting->privacy;
                $this->testSerialNo = $propertySetting->serial_no;
            }elseif($propertySetting->property->name == 'PROJECT'){
                $this->projectId = $propertySetting->id;
                $this->projectStatus = $propertySetting->status;
                $this->projectPrivacy = $propertySetting->privacy;
                $this->projectSerialNo = $propertySetting->serial_no;
            }elseif($propertySetting->property->name == 'VOLANTEER_SOCIALWORK'){
                $this->volanteerSocialworkId = $propertySetting->id;
                $this->volanteerSocialworkStatus = $propertySetting->status;
                $this->volanteerSocialworkPrivacy = $propertySetting->privacy;
                $this->volanteerSocialworkSerialNo = $propertySetting->serial_no;
            }elseif($propertySetting->property->name == 'EXTRA_CURRICULUMN'){
                $this->extraCurriculumnId = $propertySetting->id;
                $this->extraCurriculumnStatus = $propertySetting->status;
                $this->extraCurriculumnPrivacy = $propertySetting->privacy;
                $this->extraCurriculumnSerialNo = $propertySetting->serial_no;
            }elseif($propertySetting->property->name == 'RECOMMANDATION'){
                $this->recommandationId = $propertySetting->id;
                $this->recommandationStatus = $propertySetting->status;
                $this->recommandationPrivacy = $propertySetting->privacy;
                $this->recommandationSerialNo = $propertySetting->serial_no;
            }
        }

		$this->editMode = true;
    }

    public function update()
    {
    	if($this->properties && count($this->properties) > 0)
    	{
    		foreach ($this->properties as $k => $id) {
	    		$profileProperty = ProfileSettingsModel::with('property')->find($id);
	    		
	    		if($profileProperty->property->name == 'DOB'){
	    			$profileProperty->status = $this->dobStatus;
	    			$profileProperty->privacy = $this->dobPrivacy;
	    			$profileProperty->update();
	    		}elseif($profileProperty->property->name == 'CONTACT_INFO'){
	    			$profileProperty->status = $this->contactInfoStatus;
	    			$profileProperty->privacy = $this->contactInfoPrivacy;
	    			$profileProperty->update();
	    		}elseif($profileProperty->property->name == 'SOCIAL_NETWORK'){
	    			$profileProperty->status = $this->socialNetworkStatus;
	    			$profileProperty->privacy = $this->socialNetworkPrivacy;
	    			$profileProperty->update();
	    		}elseif($profileProperty->property->name == 'INTEREST'){
	    			$profileProperty->status = $this->interestStatus;
	    			$profileProperty->privacy = $this->interestPrivacy;
	    			$profileProperty->update();
	    		}elseif($profileProperty->property->name == 'EDUCATION'){
	    			$profileProperty->status = $this->educationStatus;
	    			$profileProperty->privacy = $this->educationPrivacy;
	    			$profileProperty->serial_no = $this->educationSerialNo;
	    			$profileProperty->update();
	    		}elseif($profileProperty->property->name == 'EXPERIENCE'){
	    			$profileProperty->status = $this->experienceStatus;
	    			$profileProperty->privacy = $this->experiencePrivacy;
	    			$profileProperty->serial_no = $this->experienceSerialNo;
	    			$profileProperty->update();
	    		}elseif($profileProperty->property->name == 'LANGUAGE'){

app/Http/Livewire/User/Inc/Sidebar.php
<?php

namespace App\Http\Livewire\User\Inc;

use Livewire\Component;

class Sidebar extends Component
{
	public $data;

    public function render()
    {
        return view('livewire.user.inc.sidebar');
    }
}

resources/views/dboard/inc/header.blade.php
@php $appInfo = appInfo() @endphp
    <button id="sidebarTogglerBtn" class="btn btn-xs btn-dark"><i class="fa fa-bars"></i></button>
    <nav id="topNavbar" class="navbar navbar-expand-md bg-dark navbar-dark shadow-sm fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ $appInfo && $appInfo->name ? $appInfo->name : config('app.name') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">
                    
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('home') }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('messages') }}">Messages</a>
                    </li>
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->user_name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu bg-dark dropdown-menu-right" aria-labelledby="navbarDropdown">
                                
                                @if(Auth::user()->weight >= 79.99)
                                <a href="{{ route('admin.dboard') }}" class="dropdown-item text-light bg-danger"><i class="fa fa-dashboard"></i> Dashboard</a>
                                @endif

                                <a href="{{ route('user.profile') }}" class="dropdown-item text-light"><i class="fa fa-user"></i> Profile</a>
                                <a class="dropdown-item text-light" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();"><i class="fa fa-sign-out"></i>
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

resources/views/dboard/inc/sidebar.blade.php
        <!-- Sidebar -->
        <div class="sidebar-nav">
            <span>
                <a class="sidebar-link" href="">Dashboard</a>
            </span>
            <span>
                <a class="sidebar-link" href="#">App Info</a>

            </span>
            <span>
                <a class="sidebar-link" href="#">Users</a>
            </span>
            <span>
                <a class="sidebar-link" href="#">Recruiters</a>
            </span>
        </div>
    